# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
